package org.example;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.Random;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * The Gatherer class provides functionality to generate and analyze chthonic creatures.
 * It includes methods to generate creatures with random attributes,
 * create an infinite stream of these creatures, and analyze their attack powers
 * to identify data points and outliers.
 */
public class Gatherer {
    private static final List<String> NAMES = Arrays.asList("Polyphemos", "Derek", "Medusa", "Dracula", "Lamia", "Mavka");
    private static final List<String> TYPES = Arrays.asList("Cyclops", "Werewolf", "Gorgon", "Vampire", "Witch", "Mermaid");
    private static final Random RANDOM = new Random();

    /**
     * Generates a random chthonic creature with a name, type, first mention date, and attack power.
     * The name and type are chosen randomly from predefined lists, and the first mention date
     * is generated by subtracting a random number of years from the current date.
     * The attack power is a random integer between 0 and 99.
     *
     * @return A new randomly generated ChthonicCreature
     */
    private static ChthonicCreature generateCreature() {
        String name = NAMES.get(RANDOM.nextInt(NAMES.size()));
        String type = TYPES.get(RANDOM.nextInt(TYPES.size()));
        LocalDate firstMentionDate = LocalDate.now().minusYears(RANDOM.nextInt(2000));
        int attackPower = RANDOM.nextInt(100);
        return new ChthonicCreature(name, type, firstMentionDate, attackPower);
    }

    /**
     * Creates an infinite stream of randomly generated chthonic creatures.
     * This method uses the {@link Stream#generate(java.util.function.Supplier)}
     * method to generate an infinite sequence of creatures using the
     * {@link #generateCreature()} method.
     *
     * @return An infinite stream of randomly generated ChthonicCreature objects
     */
    public static Stream<ChthonicCreature> infiniteCreatureStream() {
        return Stream.generate(Gatherer::generateCreature);
    }

    /**
     * Analyzes a list of chthonic creatures and classifies their attack powers
     * into "data" and "outliers" categories. Outliers are determined using the
     * interquartile range (IQR) method, where any attack power outside of the
     * lower and upper bounds based on the IQR is considered an outlier.
     *
     * @param creatures A list of ChthonicCreature objects to be analyzed
     * @return A map with two entries: one for "data" (normal values) and one for "outliers" (outlier values).
     */
    public static Map<String, Long> analyzeCreatures(List<ChthonicCreature> creatures) {
        List<Integer> attackPowers = creatures.stream()
                .map(ChthonicCreature::getAttackPower)
                .sorted()
                .collect(Collectors.toList());


        if (attackPowers.size() < 4) {
            return Map.of("data", 0L, "outliers", (long) attackPowers.size());
        }


        int q1 = attackPowers.get(attackPowers.size() / 4);
        int q3 = attackPowers.get(2 * attackPowers.size() / 4);
        int iqr = q3 - q1;


        int lowerBound = q1 - iqr;
        int upperBound = q3 + iqr;


        return creatures.stream()
                .collect(Collectors.partitioningBy(
                        c -> c.getAttackPower() < lowerBound || c.getAttackPower() > upperBound,
                        Collectors.counting()
                ))
                .entrySet()
                .stream()
                .collect(Collectors.toMap(
                        e -> e.getKey() ? "outliers" : "data",
                        Map.Entry::getValue
                ));
    }

}